version: "3.9"

volumes: 
  database: {}

services: 
  postgresdb:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: taskapp
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"