GET http://localhost:5202/api/v1/test
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJwc29sYWRveWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNGIwNjkyNDItNDQxNC00MjY2LThmOGUtMDg4YzNiMjA2YThhIiwiZXhwIjoxNzAwMjAzMDI0LCJpc3MiOiJwYXVsIiwiYXVkIjoicGF1bCJ9.G41oh52tU5gb0EpkhY4KzB3MAskOoElbxl5TjjZPwgA
###
